---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-operator-sa-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-operator-sa-rolebinding
subjects:
  - kind: ServiceAccount
    name: shinyproxy-operator-sa
    namespace: shinyproxy-operator
roleRef:
  kind: Role
  name: shinyproxy-operator-sa-role
  apiGroup: rbac.authorization.k8s.io
