{
 "title": "ShinyProxy Operator Logs",
 "time": { "from": "now-30m", "timezone": "browser", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{label_app=\"shinyproxy-operator\"}, namespace)"
    }
   },
   { "name": "level", "label": "Log level", "query": "DEBUG,INFO,WARN,ERROR" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Warning Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"shinyproxy-operator\", namespace=\"$namespace\"} | pattern \"<time> [<thread>] <level> <_>\"| level=\"WARN\" |~ `(?i)$filter`)[$__interval]))"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"shinyproxy-operator\", namespace=\"$namespace\"} | pattern \"<time> [<thread>] <level> <_>\"| level=\"ERROR\" |~ `(?i)$filter`)[$__interval]))"
    }
   ]
  },
  {
   "title": "ShinyProxy Operator Logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{app=\"shinyproxy-operator\", namespace=\"$namespace\"} | pattern \"<time> [<thread>] <level> <_>\"| level=~\"$level\" |~ `(?i)$filter`"
    }
   ]
  }
 ]
}