{
 "title": "ShinyProxy Logs",
 "time": { "from": "now-30m", "timezone": "browser", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(absolute_users_logged_in{shinyproxy_realm=~\".+\"}, namespace)"
    }
   },
   {
    "name": "realm",
    "query": {
     "query": "label_values(absolute_users_logged_in{namespace=~\"$namespace\"}, shinyproxy_realm)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(absolute_users_logged_in{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\"}, shinyproxy_instance)"
    }
   },
   { "name": "level", "label": "Log level", "query": "DEBUG,INFO,WARN,ERROR" },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Warning Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"shinyproxy\", namespace=\"$namespace\", sp_realm_id=\"$realm\", sp_instance=~\"$instance\"} | regexp \".*(?P<level>(DEBUG)|(INFO)|(WARN)|(ERROR)).*\" | level=\"WARN\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"shinyproxy\", namespace=\"$namespace\", sp_realm_id=\"$realm\", sp_instance=~\"$instance\"} | regexp \".*(?P<level>(DEBUG)|(INFO)|(WARN)|(ERROR)).*\" | level=\"ERROR\")[$__interval]))"
    }
   ]
  },
  {
   "title": "ShinyProxy logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{app=\"shinyproxy\", namespace=\"$namespace\", sp_realm_id=\"$realm\", sp_instance=~\"$instance\"} | regexp \".*(?P<level>(DEBUG)|(INFO)|(WARN)|(ERROR)).*\" | level=~\"$level\""
    }
   ]
  }
 ]
}