{
 "title": "ShinyProxy Usage",
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values({shinyproxy_realm=~\".+\"}, namespace)"
    }
   },
   {
    "name": "realm",
    "query": {
     "query": "label_values({namespace=~\"$namespace\"}, shinyproxy_realm)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\"}, shinyproxy_instance)"
    }
   },
   {
    "name": "spec_id",
    "label": "app",
    "query": {
     "query": "label_values({namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\"}, spec_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Startup Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(startupTime_seconds_sum{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) / sum(rate(startupTime_seconds_count{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id)",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  {
   "title": "Usage Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(usageTime_seconds_sum{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) / sum(rate(usageTime_seconds_count{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id)",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  {
   "title": "Apps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (spec_id) (max by (shinyproxy_instance, spec_id) (absolute_apps_running{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\",spec_id=~\"$spec_id\"}))",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (shinyproxy_realm) (absolute_users_logged_in{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\"})",
     "legendFormat": "Users ({{shinyproxy_realm}})"
    }
   ]
  },
  {
   "title": "Users Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (shinyproxy_realm) (absolute_users_active{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\"})",
     "legendFormat": "Users ({{shinyproxy_realm}})"
    }
   ]
  },
  {
   "title": "Auth failure rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(authFailed_total{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\"}[$__rate_interval])) != 0"
    }
   ]
  },
  {
   "title": "Start failure rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(startFailed_total{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\"}[$__rate_interval])) != 0"
    }
   ]
  }
 ]
}