apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  volumeClaimTemplates:
    - metadata:
        name: export
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 30Gi
