apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-k8s.monitoring.svc:9090
    version: 1
  - name: Loki
    type: loki
    access: proxy
    url: http://loki-gateway.loki.svc
    version: 1
