apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki

resources:
- resources/loki.namespace.yaml
- ../../bases/loki

configMapGenerator:
- behavior: replace
  files:
  - config.yaml=configs/config.yaml
  name: loki
  namespace: loki

patches:
- path: patches/loki.statefulset.yaml

images:
  - name: docker.io/grafana/loki
    newName: docker.io/grafana/loki
    newTag: 3.4.3
