apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki

resources:
  - resources/loki.namespace.yaml
  - ../../bases/loki/base.yaml

patchesStrategicMerge:
  - patches/loki.statefulset.yaml

secretGenerator:
  - name: loki
    namespace: loki
    behavior: replace
    files:
      - loki.yaml=configs/config.yaml
