apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki
resources:
  - ../../bases/promtail/base.yaml

secretGenerator:
  - name: promtail
    behavior: replace
    files:
      - configs/promtail.yaml
