apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki
resources:
  - ../../bases/promtail

secretGenerator:
  - name: promtail
    behavior: replace
    files:
      - configs/promtail.yaml

images:
  - name: docker.io/grafana/promtail:2.9.3
    newName: docker.io/grafana/promtail
    newTag: 2.9.5
