apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-read
spec:
  template:
    spec:
      containers:
        - name: read
          args:
            - -config.file=/etc/loki/config/config.yaml
            - -target=read
            - -config.expand-env=true
          envFrom:
            - secretRef:
                name: loki-minio-secrets
      affinity:
        $patch: delete # to make it work on minikube
