apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki
resources:
  - ../../bases/alloy

configMapGenerator:
  - name: alloy
    namespace: loki
    behavior: replace
    files:
      - configs/config.alloy
