apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: shinyproxy
  namespace: monitoring
spec:
  groups:
    - name: shinyproxy
      rules:
        - record: shinyproxy:proxied_app:annotations
          expr: kube_pod_annotations{} and on (namespace, pod) kube_pod_labels{label_openanalytics_eu_sp_proxied_app="true"}
        - record: shinyproxy:delegate_app:annotations
          expr: kube_pod_annotations{} and on (namespace, pod) kube_pod_labels{label_openanalytics_eu_sp_delegate_proxy="true"}
