apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shinyproxy-operator
  namespace: monitoring
  labels:
    app: shinyproxy
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: shinyproxy
  endpoints:
    - targetPort: 9090
      path: /actuator/prometheus
