# This is based on the config file from the loki helm chart.
# Modifications are commented below

auth_enabled: false
common:
  compactor_address: 'http://loki:3100'
  path_prefix: /var/loki
  replication_factor: 1
  storage:
    filesystem:
      chunks_directory: /var/loki/loki/chunks
      rules_directory: /var/loki/rules
frontend:
  scheduler_address: ""
frontend_worker:
  scheduler_address: ""
index_gateway:
  mode: ring
limits_config:
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  split_queries_by_interval: 15m
  # Modified to have retention of 90 days
  retention_period: 90d
memberlist:
  join_members:
    - loki-memberlist
query_range:
  align_queries_with_step: true
ruler:
  storage:
    type: local
runtime_config:
  file: /etc/loki/runtime-config/runtime-config.yaml
schema_config:
  configs:
    - from: "2020-10-24"
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v11
      store: boltdb-shipper

    # ###############################################################################
    # IMPORTANT: update this date to be one day after you update Loki!              #
    # This ensures old logs are still accessible, while new logs use the new schema #
    # ###############################################################################
    - from: "2024-03-19"
      index:
        period: 24h
        prefix: loki_index_
      object_store: filesystem
      schema: v12
      store: boltdb-shipper
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
storage_config:
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
tracing:
  enabled: false

# modified to make retention work
# https://grafana.com/docs/loki/latest/setup/upgrade/#240
compactor:
  retention_enabled: true
