# This is based on the config file from the loki helm chart.
# Modifications are commented below

auth_enabled: false
bloom_build:
  builder:
    planner_address: ""
  enabled: false
bloom_gateway:
  client:
    addresses: ""
  enabled: false
chunk_store_config:
  chunk_cache_config:
    background:
      writeback_buffer: 500000
      writeback_goroutines: 1
      writeback_size_limit: 500MB
    default_validity: 0s
    memcached:
      batch_size: 4
      parallelism: 5
    memcached_client:
      addresses: dnssrvnoa+_memcached-client._tcp.loki-chunks-cache.loki.svc
      consistent_hash: true
      max_idle_conns: 72
      timeout: 2000ms
common:
  compactor_address: 'http://loki:3100'
  path_prefix: /var/loki
  replication_factor: 1
  storage:
    filesystem:
      chunks_directory: /var/loki/loki/chunks
      rules_directory: /var/loki/rules
frontend:
  scheduler_address: ""
  tail_proxy_url: ""
frontend_worker:
  scheduler_address: ""
index_gateway:
  mode: ring
limits_config:
  max_cache_freshness_per_query: 10m
  query_timeout: 300s
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  split_queries_by_interval: 15m
  volume_enabled: true
  # Modified to have retention of 90 days
  retention_period: 90d
memberlist:
  join_members:
    - loki-memberlist
pattern_ingester:
  enabled: false
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      background:
        writeback_buffer: 500000
        writeback_goroutines: 1
        writeback_size_limit: 500MB
      default_validity: 12h
      memcached_client:
        addresses: dnssrvnoa+_memcached-client._tcp.loki-results-cache.loki.svc
        consistent_hash: true
        timeout: 500ms
        update_interval: 1m
ruler:
  storage:
    type: local
  wal:
    dir: /var/loki/ruler-wal
runtime_config:
  file: /etc/loki/runtime-config/runtime-config.yaml
schema_config:
  configs:
    - from: "2020-10-24"
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v11
      store: boltdb-shipper

    # ###############################################################################
    # IMPORTANT: update this date to the date you had previously configured.        #
    # This ensures old logs are still accessible, while new logs use the new schema #
    # New deployments can remove this entry                                         #
    # ###############################################################################
    - from: "2024-03-19"
      index:
        period: 24h
        prefix: loki_index_
      object_store: filesystem
      schema: v12
      store: boltdb-shipper
    # ###############################################################################
    # IMPORTANT: update this date to be one day after you update Loki!              #
    # This ensures old logs are still accessible, while new logs use the new schema #
    # ###############################################################################
    - from: "2025-05-07"
      index:
        period: 24h
        prefix: index_
      object_store: 'filesystem'
      schema: v13
      store: tsdb
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
storage_config:
  bloom_shipper:
    working_directory: /var/loki/data/bloomshipper
  boltdb_shipper:
    index_gateway_client:
        server_address: ""
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
  tsdb_shipper:
    index_gateway_client:
      server_address: ""
tracing:
  enabled: false

# modified to make retention work
# https://grafana.com/docs/loki/latest/setup/upgrade/#240
compactor:
  retention_enabled: true
  delete_request_store: filesystem
