apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  retention: 90d
  scrapeInterval: 30s
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
